version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: elevare-db
    restart: always
    environment:
      POSTGRES_USER: elevare_user
      POSTGRES_PASSWORD: your_strong_password # Change this to a secure password!
      POSTGRES_DB: elevare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elevare_user -d elevare_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: elevare-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      # Mount the source code for live-reloading with nodemon
      - ./backend/src:/usr/src/app/src
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elevare-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      # Mount all frontend files for live-reloading
      - ./:/usr/share/nginx/html

volumes:
  postgres_data: